### ISSUE TITLE
Fill spec.controlPlaneEndpoint

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/cluster-api-provider-vcluster#3]
Currently if no host can be found for the vcluster, the spec.controlPlaneEndpoint essentially is empty:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster
  namespace: vcluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
```

We should fallback to the in-cluster service host, which works at least for in cluster communication.
