### ISSUE TITLE
sync values stop successful provisioning

### ISSUE THREAD

**Issue by lknite** [loft-sh/cluster-api-provider-vcluster#36]
These lines apparently break things:

```
      sync:
        persistentvolumes:
          enabled: "true"
```

Without those lines the provisioning succeeds.

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vc-test
  namespace: vc-test
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vc-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vc-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vc-test
  namespace: vc-test
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: v0.13.0
    values: |
      storage:
        className: cephfs
#      sync:
#        persistentvolumes:
#          enabled: "true"
      ingress:
        enabled: "true"
        ingressClassName: "nginx"
        host: vc-test.root.k.home.net
#        annotations:
#          cert-manager\.io\/issuer: "cluster-adcs-issuer"
#          cert-manager\.io\/issuer-kind: "ClusterAdcsIssuer"
#          cert-manager\.io\/issuer-group: "adcs.certmanager.csf.nokia.com"

  kubernetesVersion: 1.24.0
```
