### ISSUE TITLE
setting VCLUSTER_HOST stops successful provisioning

### ISSUE THREAD

**Issue by lknite** [loft-sh/cluster-api-provider-vcluster#37]
It looks like the VCLUSTER_HOST value makes it through to the VCluster but that alone seems to stop it from provisioning:

```
export VCLUSTER_HOST=vc-test.root.k.home.net
```

vcluster.yaml:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vc-test
  namespace: vc-test
spec:
  controlPlaneEndpoint:
    host: "vc-test.root.k.home.net"
```

Could it be that it's checking the url to see if it resolves?  In my case I'm using an ingress so that url won't resolve until the ingress exists for a little bit and then gets an ip...

I'd like to use this because though I can get a cluster to provision the kubeconfig generated via 'clusterctl get kubeconfig ...' has a host of `server: https://vc-test.vc-test.svc:443`.  I would have expected the ingress url to be used based on the cluster-api-provider-vcluster README:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/7a57e40c-df75-40a7-bda2-8b22f245fabc/8bc927de-b47d-495e-99ea-0bcb53997fca)
