### ISSUE TITLE
Maximum Kubernetes version fixed to 1.24

### ISSUE THREAD

**Issue by everflux** [loft-sh/cluster-api-provider-vcluster#39]
### What happened?

Creating a cluster with kubernetes version 1.26 results in cluster version 1.24.

Input

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: student01
  namespace: student01-vcluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: null
      repo: null
      version: null
    values: |
      sync:
        ingresses:
          enabled: true
        networkpolicies:
          enabled: false
        #for metricsserver
        nodes:
          enabled: true
          syncAllNodes: true
        #makes SCs visible
        # hoststorageclasses:
        #   enabled: true
        persistentvolumes:
          enabled: true
      syncer:
        extraArgs:
        - --tls-san=student01.student01-vcluster
  kubernetesVersion: 1.26.0
```

Log snippet

```
1.6793202193629904e+09	DEBUG	vcluster-controller	upgrade virtual cluster helm chart student01-vcluster/student01
1.679320219363043e+09	INFO	vcluster-controller	vclusters student01-vcluster/student01 patch version defined in .spec.kubernetesVersion field will be ignored, latest supported patch version will be used
1.6793202193633888e+09	INFO	vcluster-controller	officially unsupported host server version 1.26, will fallback to virtual cluster version v1.24
1.6793202193639154e+09	INFO	vcluster-controller	Deploy virtual cluster student01-vcluster/student01 with values: sync:
  ingresses:
    enabled: true
  networkpolicies:
    enabled: false
  nodes:
    enabled: true
    syncAllNodes: true
  persistentvolumes:
    enabled: true
syncer:
  extraArgs:
  - --tls-san=student01.t9v.de
  - --tls-san=student01.student01-vcluster
vcluster:
  image: rancher/k3s:v1.24.1-k3s1

helm upgrade student01 vcluster --repo https://charts.loft.sh --version 0.11.1 --kubeconfig /tmp/62755493 --namespace student01-vcluster --install --values /tmp/4202844644
```

### What did you expect to happen?

vcluster uses 1.26

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with version 1.26

### Anything else we need to know?

The cluster was using vcluster 0.13.1 and was upgraded later.

clusterctl version
clusterctl version: &[version.Info](http://version.Info){Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"58770484dee6c99c10e32c06652e9f9643f78e9e", GitTreeState:"clean", BuildDate:"2023-03-02T15:57:13Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

The vcluster controller pod uses the following images

[docker.io/loftsh/cluster-api-provider-vcluster:0.1.3](http://docker.io/loftsh/cluster-api-provider-vcluster:0.1.3)
[gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0](http://gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0)

There is no newer image on dockerhub [https://hub.docker.com/r/loftsh/cluster-api-provider-vcluster/tags](https://hub.docker.com/r/loftsh/cluster-api-provider-vcluster/tags)

### Host cluster Kubernetes version

<details>

```
$ kubectl version
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
vanilla v1.26.3, Ubuntu 22.04.2 LTS   5.15.0-67-generic   containerd://1.6.18
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.14.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
default (k3s)
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu
Arch: AMD64
```

</details>
