### ISSUE TITLE
vcluster dont support private registry with authentication

### ISSUE THREAD

**Issue by sbasti93** [loft-sh/cluster-api-provider-vcluster#86]
I came across the following problem through a POC. When I tried to change the referencing from the official Helm Chart to a private registry (with authentication), I realised that this does not work at all.

According to the CRD, the only parameters to be set are the following: 
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: [CLUSTER_NAME]
spec:
  helmRelease:
    chart: 
      name: [CHART_NAME]
      repo: [CHART_REPO]
      version: [CHART_VERSION]
```

This means that it is not possible to pass a secret, which is required for authentication at the private registry.
There may be another way to do this, which I have not found out.
